<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Xóa sạch dữ liệu cũ để tránh trùng lặp
        Schema::disableForeignKeyConstraints();
        DB::table('products')->truncate();
        Schema::enableForeignKeyConstraints();

        $products = [
            [
                'id' => 1,
                'name' => 'Mutant Mass Extreme 2500 12lbs',
                'product_category' => 'sups',
                'description' => '1 serving Mass Extreme 2500 12lbs cung cấp: 1070 Calories, 230-231g Carbohydrate và 30g Protein. Hỗ trợ tăng cân hiệu quả. Vị ngon dễ uống.',
                'price' => 1850000,
                'image' => 'san-pham-1.jpg',
                'sku' => 'SKU-MUTANT-MASS',
                'stock_quantity' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Whey Gold Standard 5lbs',
                'product_category' => 'sups',
                'description' => 'Sữa tăng cơ tinh khiết, cung cấp 24g Protein và 5.5g BCAA mỗi khẩu phần giúp phục hồi cơ bắp nhanh chóng sau tập.',
                'price' => 1550000,
                'image' => 'san-pham-2.jpg',
                'sku' => 'SKU-WHEY-GOLD',
                'stock_quantity' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Rule 1 Whey Blend 5lbs',
                'product_category' => 'sups',
                'description' => 'Phức hợp Whey Concentrate và Isolate, hỗ trợ phát triển cơ bắp hiệu quả với 24g protein/serving, mùi vị đa dạng.',
                'price' => 1350000,
                'image' => 'san-pham-3.jpg',
                'sku' => 'SKU-RULE1-BLEND',
                'stock_quantity' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Creatine Monohydrate Ostrovit 300g',
                'product_category' => 'sups',
                'description' => 'Tăng cường sức mạnh bùng nổ, tích trữ năng lượng ATP, giúp nâng tạ nặng hơn và tăng độ phồng tế bào cơ.',
                'price' => 450000,
                'image' => 'san-pham-4.jpg',
                'sku' => 'SKU-CREATINE-OST',
                'stock_quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Xtend BCAA 90 Servings',
                'product_category' => 'sups',
                'description' => 'Cung cấp 7g BCAA với tỷ lệ 2:1:1 và Electrolytes giúp phục hồi, chống dị hóa cơ bắp, bổ sung điện giải trong lúc tập.',
                'price' => 1150000,
                'image' => 'san-pham-5.jpg',
                'sku' => 'SKU-XTEND-BCAA',
                'stock_quantity' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Pre-Workout C4 Original 30 Servings',
                'product_category' => 'sups',
                'description' => 'Tăng cường năng lượng, độ tỉnh táo, tập trung và sức bền với 150mg Caffeine, Beta-Alanine và Creatine.',
                'price' => 650000,
                'image' => 'san-pham-6.jpg',
                'sku' => 'SKU-C4-PRE',
                'stock_quantity' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Dầu cá Omega-3 Fish Oil 1000mg',
                'product_category' => 'sups',
                'description' => 'Chứa EPA và DHA hỗ trợ sức khỏe tim mạch, giảm đau viêm khớp sau tập tạ nặng và cải thiện trí não.',
                'price' => 350000,
                'image' => 'san-pham-7.jpg',
                'sku' => 'SKU-OMEGA3-OIL',
                'stock_quantity' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'ZMA (Zinc, Magnesium, Vitamin B6)',
                'product_category' => 'sups',
                'description' => 'Phục hồi hệ thần kinh, thư giãn cơ, ngăn chuột rút, cải thiện giấc ngủ sâu và hỗ trợ tăng sinh tự nhiên.',
                'price' => 550000,
                'image' => 'san-pham-8.jpg',
                'sku' => 'SKU-ZMA-RECOVERY',
                'stock_quantity' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Lipo 6 Black Ultra Concentrate',
                'product_category' => 'sups',
                'description' => 'Công thức sinh nhiệt siêu tập trung, tăng cường đốt cháy mỡ thừa và hỗ trợ quá trình siết cơ (Cutting) cực mạnh.',
                'price' => 750000,
                'image' => 'san-pham-9.jpg',
                'sku' => 'SKU-LIPO6-BURN',
                'stock_quantity' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Bánh Protein Bar (Hộp 12 thanh)',
                'product_category' => 'sups',
                'description' => 'Bữa ăn phụ cực kỳ tiện lợi, cung cấp 20g protein nhanh chóng trước hoặc sau khi tập luyện bận rộn.',
                'price' => 650000,
                'image' => 'san-pham-10.jpg',
                'sku' => 'SKU-PROBAR-BOX',
                'stock_quantity' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Vitamin D3 K2 MK7 Ostrovit',
                'product_category' => 'sups',
                'description' => 'Hỗ trợ vận chuyển và hấp thụ canxi vào xương, tăng mật độ xương khớp, phòng ngừa loãng xương hiệu quả.',
                'price' => 400000,
                'image' => 'san-pham-11.jpg',
                'sku' => 'SKU-D3K2-OST',
                'stock_quantity' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Đai lưng gánh tạ Valeo',
                'product_category' => 'gear',
                'description' => 'Bảo vệ cột sống, hỗ trợ gồng core (Intra-abdominal pressure) an toàn cho các bài tập nặng như Squat, Deadlift.',
                'price' => 250000,
                'image' => 'san-pham-12.jpg',
                'sku' => 'SKU-VALEO-BELT',
                'stock_quantity' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'Dây kéo lưng (Lifting Straps)',
                'product_category' => 'gear',
                'description' => 'Tăng độ bám, trợ lực cho cổ tay và cẳng tay trong các bài kéo (Pull) để tập trung tác động vào cơ lưng.',
                'price' => 150000,
                'image' => 'san-pham-13.jpg',
                'sku' => 'SKU-LIFT-STRAPS',
                'stock_quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'Băng quấn cổ tay (Wrist Wraps)',
                'product_category' => 'gear',
                'description' => 'Cố định khớp cổ tay, phòng tránh chấn thương hiệu quả khi thực hiện đẩy tạ nặng (Bench press, Shoulder press).',
                'price' => 200000,
                'image' => 'san-pham-14.jpg',
                'sku' => 'SKU-WRIST-WRAPS',
                'stock_quantity' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'Bình lắc Shaker Spider 500ml',
                'product_category' => 'gear',
                'description' => 'Thiết kế chống rò rỉ, kèm quả cầu lò xo giúp hòa tan Whey/Mass dễ dàng, chất liệu nhựa an toàn BPA-free.',
                'price' => 120000,
                'image' => 'san-pham-15.jpg',
                'sku' => 'SKU-SHAKER-SPIDER',
                'stock_quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'Băng bảo vệ gối (Knee Sleeves)',
                'product_category' => 'gear',
                'description' => 'Giữ ấm và trợ lực khớp gối khi Squat, giảm áp lực lên sụn chêm and dây chằng, bảo vệ đầu gối tối đa.',
                'price' => 350000,
                'image' => 'san-pham-16.jpg',
                'sku' => 'SKU-KNEE-SLEEVES',
                'stock_quantity' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'Dây kháng lực (Resistance Band)',
                'product_category' => 'gear',
                'description' => 'Bộ 5 dây cao su co giãn giúp tập mông đùi hiệu quả tại nhà, hoặc dùng để khởi động khớp vai linh hoạt trước khi tập.',
                'price' => 180000,
                'image' => 'san-pham-17.jpg',
                'sku' => 'SKU-RES-BAND',
                'stock_quantity' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'Mutant Geaar EAA 30 Servings',
                'product_category' => 'sups',
                'description' => 'Cung cấp 9 amino axit thiết ước tổng hợp protein, bổ sung chất điện giải chống dị hóa và bù nước trong lúc tập tạ.',
                'price' => 850000,
                'image' => 'san-pham-18.jpg',
                'sku' => 'SKU-MUTANT-EAA',
                'stock_quantity' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'Lăn khử mùi thể thao Old Spice',
                'product_category' => 'gear',
                'description' => 'Ngăn tiết mồ hôi, kháng khuẩn, giữ cơ thể khô thoáng và tự tin trong suốt buổi tập tạ cường độ cao tại phòng.',
                'price' => 160000,
                'image' => 'san-pham-19.jpg',
                'sku' => 'SKU-OLDSPICE-DEO',
                'stock_quantity' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'Túi xách thể thao KOR Duffle',
                'product_category' => 'gear',
                'description' => 'Túi gym chống nước, có ngăn đựng giày riêng biệt thoát khí, chứa phụ kiện, quần áo, bình lắc cực kỳ rộng rãi.',
                'price' => 320000,
                'image' => 'san-pham-20.jpg',
                'sku' => 'SKU-KOR-DUFFLE',
                'stock_quantity' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);
    }
}